name: Build CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Build package
        run: npm run package
      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v4.9.1
        with:
          commit_message: ":rocket: Deploy new version [skip ci]"
          commit_user_name: Finding Anand
          commit_user_email: bot@anandchowdhary.com
          commit_author: Finding Anand <bot@anandchowdhary.com>
